arch: amd64

language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

script:
  - java --version
  - mvn -Dtest=logic/** test
after_success:
  - bash <(curl -s https://codecov.io/bash)